title: "Vahid Moeinifar - Personal Portfolio"
description: "Personal portfolio website showcasing my projects and skills"
url: "https://vahidmoeinifar.github.io"
theme: null
markdown: kramdown

# Social links
github_username: https://github.com/vahidmoeinifar
linkedin_username: https://www.linkedin.com/feed/

# Build settings
sass:
  sass_dir: assets/css